version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: /Api/N5Challenge.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  client:
    stdin_open: true
    environment:
      - REACT_APP_BACKEND_URL_BASE=http://localhost:8080
    build:
      context: ./Client
      dockerfile: Dockerfile      
    volumes:
      - /app/node_modules
      - ./Client:/app
    ports:
      - 3000:3000
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"

    environment:
        SA_PASSWORD: "P@ssw0rd"
        ACCEPT_EULA: "Y"